services:
  sc_server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sc_server-container
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/sc_DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    restart: always

  database:
    image: mariadb:10.7
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sc_DB
    ports:
      - "3306:3306" # Porta MariaDB esposta
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--user=root",
          "--password=password",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
# secrets:
#   keystore-password:
#     file: ./secret/keystore-password.txt
