api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: "websecure"
    #       scheme: "https"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
log:
  level: INFO
# certificatesResolvers:
# le:
#   acme:
#     email: "slaitroc@gmail.com"
#     storage: "/etc/traefik/acme.json"
#     tlsChallenge: {}
#     httpChallenge:
#       entryPoint: "web"
