services:
  sc_server-service:
    image: openjdk:21-jdk-slim
    container_name: sc_server-container
    working_dir: /sc_server
    entrypoint: ["java", "-jar", "/sc_server/sc_server.jar"]
    volumes:
      - ./sc_server/target/sc_server.jar:/sc_server/sc_server.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database-service:3306/sc_DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application-container.rule=Host(`localhost`) &&  PathPrefix(`/application-api`)" # Regola per l'API e dichiarazione del nome del container
      - "traefik.http.routers.application-container.service=application-service" # dichiaro il nome del Servizio per l'API
      - "traefik.http.routers.application-container.entrypoints=web" # Usa l'entrypoint HTTPS
      # - "traefik.http.routers.application-container.entrypoints=websecure" # Usa l'entrypoint HTTPS
      # - "traefik.http.routers.application-container.tls=true" # Forza l'uso di TLS
      # - "traefik.http.routers.application-container.tls.certresolver=le" # Risolutore ACME per i certificati
      - "traefik.http.services.application-service.loadbalancer.server.port=8443" # Porta interna del server

    networks:
      - traefik-network
    depends_on:
      - database-service
    restart: always

  database-service:
    image: mariadb:10.7
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sc_DB
    ports:
      - "3306:3306" # Porta MariaDB esposta
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--user=root",
          "--password=password",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - platform_db_data:/var/lib/mysql
    networks:
      - traefik-network

  traefik-service:
    image: traefik:latest
    container_name: traefik-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Accesso al socket Docker
      - "./proxy/traefik.yaml:/etc/traefik/traefik.yaml"
    labels:
      # DASHBOARD
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      # - "traefik.http.routers.traefik.tls.certresolver=le"
      # - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

      # MIDDLEWARE AUTH
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$dtvOjBZO$$sfd2sw28jzU244hTPqN/B."

    networks:
      - traefik-network

networks:
  traefik-network:
    driver: bridge

volumes:
  platform_db_data:
