@startuml UserLogIn
skinparam sequenceMessageAlign center
participant  Presentation
entity      Proxy
participant Authenticator
entity AuthProvider

activate Presentation
Presentation -> Proxy : POST api/auth/create-token
activate Proxy
group <color:purple> InsertCredentials(UserCredentials)
Proxy -> Authenticator : POST api/auth/insert-credentials
activate Authenticator
Authenticator -> AuthProvider : validateCredentials(UserCredentials)
activate AuthProvider
AuthProvider --> Authenticator : success
deactivate AuthProvider
Authenticator --> Proxy : CallResult 
deactivate Authenticator
end
alt CallResult == 400 BadRequest
Proxy --> Presentation : 400 BadRequest : Error
end
group <color:purple> GenerateToken(UserCredentials)
Proxy -> Authenticator : POST api/auth/insert-credentials
activate Authenticator
Authenticator -> AuthProvider : generateToken(UserCredentials)
activate AuthProvider
AuthProvider --> Authenticator : Token
deactivate AuthProvider
Authenticator --> Proxy : 201 Created : Token
deactivate Authenticator
end
Proxy --> Presentation : 201 Created : Token