@startuml 
skinparam sequenceMessageAlign center

participant Presentation
entity Proxy
participant APIController
participant NotificationManager
participant NotificationEntityManager
database NotificationDB
entity NotificationProvider

activate Presentation
group <color:purple> Request Device Token
Presentation -> NotificationProvider : getDeviceToken(AppInfo)
activate NotificationProvider
NotificationProvider --> Presentation : DeviceToken
deactivate NotificationProvider
Presentation -> Proxy : POST api/notify/private/new-device-token
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : POST api/notify/private/new-device-token
activate APIController
APIController -> NotificationManager : insertOrUpdateDT\n(DeviceToken, UserID, DeviceID)
activate NotificationManager
NotificationManager -> NotificationEntityManager : insertOrUpdateDT\n(DeviceToken, UserID, DeviceID)
activate NotificationEntityManager
NotificationEntityManager -> NotificationDB : insertOrUpdate\n(DeviceToken, UserID, DeviceID)
activate NotificationDB
NotificationDB --> NotificationEntityManager : success
deactivate NotificationDB
NotificationEntityManager --> NotificationManager : success
deactivate NotificationEntityManager
NotificationManager --> APIController : success
deactivate NotificationManager
APIController --> Proxy : 200 OK
deactivate APIController
Proxy --> Presentation : 200 OK
deactivate Proxy
Presentation -> Presentation : saveDeviceToken(DeviceToken)
end

@enduml