@startuml CompanySubmitsInterview
skinparam sequenceMessageAlign center
actor       Company
participant Presentation
entity      Proxy
participant APIController
participant InterviewsManager
participant PlatformEntityManager
participant NotificationManager 
database    PlatformDBMS
activate Company
Company -> Presentation : clickSendInterview()
activate Presentation
Presentation -> Proxy ++ : POST api/interviews/private/send-interview/{InterviewID}
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : POST api/interviews/private/send-interview/{InterviewID}
activate APIController
APIController -> InterviewsManager : submitInterview(InterviewID, InterviewData, UserID)
activate InterviewsManager
InterviewsManager -> PlatformEntityManager : submitInterview(InterviewID, InterviewData, UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : success
deactivate PlatformDBMS
PlatformEntityManager --> InterviewsManager : success
deactivate PlatformEntityManager
InterviewsManager --> APIController : success
deactivate InterviewsManager
APIController --> NotificationManager : notifyUser(UserIDs, Data)
activate NotificationManager
NotificationManager -> NotificationManager : <color:purple> sendNotification(UserIDs, Data)
NotificationManager --> APIController : success
deactivate NotificationManager
APIController --> Proxy : 200 OK
deactivate APIController
Proxy --> Presentation : 200 OK
deactivate Proxy
Presentation --> Company : displayInterviewSendedMsg()
deactivate Presentation





