@startuml CompanyCreateTemplateInterview
skinparam sequenceMessageAlign center
actor       Company
participant Presentation
entity      Proxy
participant APIController
participant InterviewsManager
participant PlatformEntityManager
database    PlatformDBMS

activate Company
Company -> Presentation : clickSaveInterview()
activate Presentation
Presentation -> Proxy : POST api/interviews/private/\nsave-template-interview/{InterviewID}
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : POST api/interviews/private/\nsave-template-interview/{InterviewID}
activate APIController
APIController -> InterviewsManager : saveTemplateInterview\n(InterviewTemplate, UserID)
activate InterviewsManager
InterviewsManager -> PlatformEntityManager : saveInterview\n(InterviewTemplate, UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : insert(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : success
deactivate PlatformDBMS
PlatformEntityManager --> InterviewsManager : success
deactivate PlatformEntityManager
InterviewsManager --> APIController : success
deactivate InterviewsManager
APIController --> Proxy : 201 Created
deactivate APIController
Proxy --> Presentation : 201 Created
Presentation --> Company : displayInterviewSavedMsg()
deactivate Presentation
