@startuml 13StudentSeeSpontaneousApplications
skinparam sequenceMessageAlign center
actor       Student
participant Presentation
entity      Proxy
participant APIController
participant SubmissionsManager
participant PlatformEntityManager
database    PlatformDBMS

activate Student
Student -> Presentation : clickDashboardSpontaneous\nApplicationsPage()
activate Presentation
Presentation -> Proxy : GET api/applications/private/\nget-spontaneous-applications
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : GET api/applications/private/\nget-spontaneous-applications
activate APIController
APIController -> SubmissionsManager : getSpontaneousApplications\n(StudentID)
activate SubmissionsManager
SubmissionsManager -> PlatformEntityManager : getSpontaneousApplications\n(StudentID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : result
deactivate PlatformDBMS
PlatformEntityManager --> SubmissionsManager : result
deactivate PlatformEntityManager
SubmissionsManager --> APIController : Applications
deactivate SubmissionsManager
APIController --> Proxy : 200 OK : Applications
deactivate APIController
Proxy --> Presentation : 200 OK : Applications
deactivate Proxy
Presentation --> Student : displaySpontaneousApplications()
deactivate Presentation
@enduml