@startuml 14ParticipantSeesMatches
skinparam sequenceMessageAlign center
actor       Participant
participant Presentation
entity      Proxy
participant APIController
participant RecommendationProcess
participant PlatformEntityManager
database    PlatformDBMS

activate Participant
Participant -> Presentation : clickDashboard\nRecommendationPage()
activate Presentation
Presentation -> Proxy : GET api/applications/\nprivate/get-matches
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : GET api/applications/\nprivate/get-matches
activate APIController
APIController -> RecommendationProcess : getMatches(UserID)
activate RecommendationProcess
RecommendationProcess -> PlatformEntityManager : getMatches(UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : result
deactivate PlatformDBMS
PlatformEntityManager --> RecommendationProcess : result
deactivate PlatformEntityManager
RecommendationProcess --> APIController : Matches
deactivate RecommendationProcess
APIController --> Proxy : 200 OK : Matches
deactivate APIController
Proxy --> Presentation : 200 OK : Matches
deactivate Proxy
Presentation --> Participant : displayMatches()
deactivate Presentation
@enduml


