@startuml UserOpensComplaint
skinparam sequenceMessageAlign center
actor       User
participant  Presentation
entity      Proxy
participant APIController
participant CommunicationManager
participant PlatformEntityManager
database    PlatformDBMS

activate User
User -> Presentation : clickComplaint(CommID)
activate Presentation
Presentation -> Proxy : GET api/comm/private/communications/{CommID}?<params>
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : GET api/comm/private/communications/{CommID}?<params>
activate APIController
APIController -> APIController : verifyCallParameters()
alt Wrong API Call Parameters
APIController --> Proxy : 400 Bad Request : Error
Proxy --> Presentation : 400 Bad Request : Error
Presentation --> User : displayErrorMessage()
end
note right of APIController : Alternatives to let the Presentation easily handle different data 
group alternatives url parameters 
else <param> to only get the communication type
APIController -> CommunicationManager : getType(CommID)
activate CommunicationManager
CommunicationManager -> PlatformEntityManager : getType(CommID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
else <param> to only get the communication messages
APIController -> CommunicationManager : getMessages(CommID)
CommunicationManager -> PlatformEntityManager : getMessages(CommID)
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
else <param> to get all communication data
APIController -> CommunicationManager : getCommunication(CommID)
CommunicationManager -> PlatformEntityManager : getCommunication(CommID)
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
end
PlatformDBMS --> PlatformEntityManager : result
deactivate PlatformDBMS
PlatformEntityManager --> CommunicationManager : result
deactivate PlatformEntityManager
CommunicationManager --> APIController : Result
deactivate CommunicationManager
APIController --> Proxy : 200 OK : Result
deactivate APIController
Proxy --> Presentation : 200 OK : Result
deactivate Proxy
Presentation --> User : displayResult(Result)
deactivate Presentation



