@startuml UserOpensComplaint
skinparam sequenceMessageAlign center
actor       Participant
participant  Presentation
entity      Proxy
participant APIController
participant CommunicationManager
participant PlatformEntityManager
participant NotificationManager
database    PlatformDBMS

' I'm assuming the user has already typed the text of the complaint
' and the api call contains the text of the complaint

activate Participant
Participant -> Presentation : clickCreateNewComplaint()
activate Presentation
Presentation -> Proxy : POST api/comm/private/\ncreate?isComplain=true
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : POST api/comm/private/\ncreate?isComplain=true
activate APIController
APIController -> CommunicationManager : createComplaint\n(UserID, Communication)
activate CommunicationManager
CommunicationManager -> PlatformEntityManager : insert(Communication, UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : insert(Communication, UserID)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : success
deactivate PlatformDBMS
PlatformEntityManager --> CommunicationManager : success
deactivate PlatformEntityManager
CommunicationManager --> APIController : success
deactivate CommunicationManager
APIController -> NotificationManager : notifyUser(Data, UserIDs)
activate NotificationManager
NotificationManager -> NotificationManager : <color:purple> sendNotification(UserIDs, Data)
NotificationManager --> APIController : success
deactivate NotificationManager
deactivate CommunicationManager
APIController --> Proxy : 201 Created
deactivate APIController
Proxy --> Presentation : 201 Created
deactivate Proxy
Presentation --> Participant : displayNewComplaints()
deactivate Presentation



