@startuml UserLogIn
skinparam sequenceMessageAlign center
actor       User
participant  Presentation
entity      Proxy
participant Authenticator
entity AuthProvider

activate User
User -> Presentation : enterCredentials(UserCredentials)
activate Presentation
Presentation -> Proxy : POST api/auth/login
activate Proxy
group <color:purple> ValidateCredentials(UserCredentials)
Proxy -> Authenticator : POST api/auth/validate-credentials
activate Authenticator
Authenticator -> AuthProvider : validateCredentials(UserCredentials)
activate AuthProvider
AuthProvider --> Authenticator : isValid
deactivate AuthProvider
Authenticator --> Proxy : 200 OK : isValid
deactivate Authenticator
end
alt isValid==false
Proxy --> Presentation : 401 Unauthorized : Error Message
Presentation --> User : displayErrorMessage()
end
Proxy -> Proxy : <color:purple> GenerateToken(UserCredentials)
Proxy --> Presentation : 201 Created : Token
deactivate Proxy
Presentation -> Presentation : saveToken(Token)
Presentation --> User : redirectDashboard()
deactivate Presentation
deactivate User
@enduml



