@startuml UserLogIn
skinparam sequenceMessageAlign center
actor       User
participant  Presentation
entity      Proxy
participant Authenticator
participant APIController
participant AccountManager
participant PlatformEntityManager
database    PlatformDBMS

activate User
User -> Presentation : enterCredentials(username, password)
activate User
activate Presentation
Presentation -> Proxy : POST api/auth/login
activate Proxy
Proxy -> Authenticator : POST api/auth/validateCredentials
activate Authenticator
Authenticator -> Authenticator : validateCredentials(username, password)
alt Credentials Invalid
    Authenticator --> Proxy : 401 Unauthorized : Invalid Credentials
    Proxy --> Presentation : 401 Unauthorized : Error Message
    Presentation --> User !! : displayErrorMessage()
end
Authenticator -> Authenticator : GenerateToken()
Authenticator --> Proxy : 200 OK : UserID, Token
deactivate Authenticator
Proxy -> APIController : POST api/common/account/session
activate APIController
APIController -> AccountManager : startSession(UserID)
activate AccountManager
AccountManager -> PlatformEntityManager : getUserDetails(UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : BuildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : User Details
deactivate PlatformDBMS
PlatformEntityManager -->  AccountManager : User Details
deactivate PlatformEntityManager
AccountManager --> APIController : Session Started
deactivate AccountManager
APIController --> Proxy : 200 OK : SessionInfo
deactivate APIController
Proxy --> Presentation : 200 OK : SessionInfo, Token
deactivate Proxy
Presentation -> Presentation : SaveToken()
Presentation --> User : displayDashboard()
deactivate Presentation
deactivate User
@enduml



