@startuml UserViewsCompanyInternships
skinparam sequenceMessageAlign center
actor       User
participant  Presentation
entity      Proxy
participant APIController
participant SubmissionManager
participant PlatformEntityManager
database    PlatformDBMS

activate User
User -> Presentation : clickViewCompanyInternships()
activate Presentation
Presentation -> Proxy : GET api/comm/private/internships/full?<param>
activate Proxy
Proxy -> Proxy  : <color:purple> Authentication()
Proxy -> APIController : GET api/comm/private/internships/full?<param>
activate APIController
APIController -> APIController : verifyCallParameters()
APIController -> SubmissionManager : getInternshipsByCompany(CompanyID)
activate SubmissionManager
SubmissionManager -> PlatformEntityManager : getInternshipsByCompany(CompanyID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : List of Internships
deactivate PlatformDBMS
PlatformEntityManager --> SubmissionManager : List of Internships
deactivate PlatformEntityManager
SubmissionManager --> APIController : List of Internships
deactivate SubmissionManager
APIController --> Proxy : 200 OK : List of Internships
deactivate APIController
Proxy --> Presentation : 200 OK : List of Internships
deactivate Proxy
Presentation --> User : displayInternships()
deactivate Presentation
deactivate User
@enduml
