@startuml UserViewsCompanyInternships
skinparam sequenceMessageAlign center
actor       User
participant  Presentation
entity      Proxy
participant APIController
participant SubmissionManager
participant PlatformEntityManager
database    PlatformDBMS

activate User
User -> Presentation : clickViewStudentCV()
activate Presentation
Presentation -> Proxy : GET api/sub/private/cv/{StudentID}
activate Proxy
Proxy -> Proxy  : <color:purple> Authentication

Proxy -> APIController : GET api/sub/private/cv/{StudentID}
activate APIController
APIController -> SubmissionManager : getCVByStudent(StudentID)
activate SubmissionManager
SubmissionManager -> PlatformEntityManager : getCVByStudent(StudentID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : result
deactivate PlatformDBMS
PlatformEntityManager --> SubmissionManager : result
deactivate PlatformEntityManager
SubmissionManager --> APIController : CV
deactivate SubmissionManager
APIController --> Proxy : 200 OK : CV
deactivate APIController
Proxy --> Presentation : 200 OK : CV
deactivate Proxy
Presentation --> User : displayCV()
deactivate Presentation
deactivate User
@enduml
