@startuml AcceptRecommendation
skinparam sequenceMessageAlign center
actor       Participant
participant  Presentation
entity      Proxy
participant APIController
participant RecommendationManager
participant InterviewManager
participant PlatformEntityManager
participant NotificationManager
database    PlatformDBMS

activate Participant
Participant -> Presentation : pressAcceptRecommendation()
activate Presentation
Presentation -> Proxy : POST api/recommendations/private/\n{RecommendationID}/accept
activate Proxy
Proxy -> Proxy : <color:purple> Authentication()

Proxy -> APIController ++ : POST api/recommendations/private/\n{RecommendationID}/accept
APIController -> RecommendationManager ++ : acceptRecommendation(RecommendationID, UserID1)
RecommendationManager -> PlatformEntityManager ++ : updateAndGetRecommendation(RecommendationID, UserID1)
PlatformEntityManager -> PlatformDBMS ++ : update&query(RecommendationID, UserID1)
PlatformDBMS --> PlatformEntityManager -- : result
PlatformEntityManager --> RecommendationManager -- : result
RecommendationManager --> APIController -- : RecommendationData

alt Other Party Already Accepted
    APIController -> NotificationManager ++ : notifyUser(UserID2, Data)
    NotificationManager -> NotificationManager : <color:purple> sendNotification(UserID2, Data)
    NotificationManager --> APIController -- : success
    APIController -> InterviewManager ++ : createInterview(UserID1, UserID2)
    InterviewManager -> PlatformEntityManager ++ : createInterview(UserID1, UserID2)
    PlatformEntityManager -> PlatformDBMS ++ : insert(UserID1, UserID2)
    PlatformDBMS --> PlatformEntityManager -- : success
    PlatformEntityManager --> InterviewManager -- : success
    InterviewManager --> APIController -- : success
end
alt FeedbackMechanism triggered
    APIController --> Proxy : 201 Created  : askFeedback
    Proxy --> Presentation : 200 Created : askFeedback
    Presentation --> Participant : displayFeedbackForm()
end

APIController --> Proxy : 201 Created  
deactivate APIController
Proxy --> Presentation : 201 Created 
deactivate Proxy
Presentation --> Participant : displaySuccessMessage()

@enduml
