@startuml SubmitFeedback
skinparam sequenceMessageAlign center
actor       Participant
participant  Presentation
entity      Proxy
participant APIController
participant FeedbackMechanism
participant PlatformEntityManager
database    PlatformDBMS

activate Participant
activate Presentation
Participant -> Presentation  : pressSubmitFeedback()
Presentation -> Proxy ++ : PUT api/feedback/private/\n{RecommendationID}/submit
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController ++ : PUT api/feedback/private/\n{RecommendationID}/submit
APIController -> FeedbackMechanism ++ : submitFeedback\n(RecommendationID)
FeedbackMechanism -> PlatformEntityManager ++ : saveFeedback\n(RecommendationID)
PlatformEntityManager -> PlatformDBMS ++ : insertOrUpdate\n(Feedback, RecommendationID)
PlatformDBMS --> PlatformEntityManager -- : success
PlatformEntityManager --> FeedbackMechanism -- : success
FeedbackMechanism -> PlatformEntityManager ++ : retrieveRecommendationParameters()
PlatformEntityManager -> PlatformDBMS ++ : buildAndExecuteQuery\n(Query, Class)
PlatformDBMS --> PlatformEntityManager -- : result
PlatformEntityManager --> FeedbackMechanism -- : result
FeedbackMechanism -> FeedbackMechanism : computeRecommendationParameters\n(RecommendationParameters)
FeedbackMechanism -> PlatformEntityManager ++ : updateRecommendationParameters\n(RecommendationParameters)
PlatformEntityManager -> PlatformDBMS ++ : update\n(RecommendationParameters)
PlatformDBMS --> PlatformEntityManager -- : success
PlatformEntityManager --> FeedbackMechanism -- : success
FeedbackMechanism --> APIController -- : success
APIController --> Proxy -- : 200 OK  
Proxy --> Presentation -- : 200 OK 
Presentation --> Participant -- : displaySuccessMessage()
@enduml