@startuml StudentSubmitInterview
skinparam sequenceMessageAlign center
actor       Student
participant Presentation
entity      Proxy
participant APIController
participant InterviewsManager
participant PlatformEntityManager
participant NotificationManager 
database    PlatformDBMS

activate Student
Student -> Presentation : clickSendInterviewAnswer()
activate Presentation
Presentation -> Proxy : POST api/interviews/private/send-answer/{InterviewID}
activate Proxy
Proxy -> Proxy : <color:purple> Authentication
Proxy -> APIController : POST api/interviews/private/send-answer/{InterviewID}
activate APIController
APIController -> APIController : verifyCallParameters()
alt Wrong API Call Parameters
    APIController --> Proxy : 400 Bad Request : Error
    Proxy --> Presentation : 400 Bad Request : Error
    Presentation --> Student : displayErrorMessage()
end 
APIController -> InterviewsManager : submitInterviewAnswers(InterviewID, Answer, UserID)
activate InterviewsManager
InterviewsManager -> PlatformEntityManager : submitInterviewAnswers(InterviewID, Answer, UserID)
activate PlatformEntityManager
PlatformEntityManager -> PlatformDBMS : buildAndExecuteQuery(Query, Class)
activate PlatformDBMS
PlatformDBMS --> PlatformEntityManager : success
deactivate PlatformDBMS
PlatformEntityManager --> InterviewsManager : success
deactivate PlatformEntityManager
InterviewsManager --> APIController : success
deactivate InterviewsManager
APIController --> NotificationManager : notifyUser(UserIDs, Data)
activate NotificationManager
NotificationManager -> NotificationManager : <color:purple> sendNotification(UserIDs, Data)
NotificationManager --> APIController : success
deactivate NotificationManager
APIController --> Proxy : 200 OK
deactivate APIController
Proxy --> Presentation : 200 OK
deactivate Proxy
Presentation --> Student : displayInterviewSendedMsg()
deactivate Presentation






