package click.studentandcompanies.dto;

public enum DTOTypes {
    CV,
    ERROR,
    MESSAGE,
    ACCOUNT,
    STUDENT,
    FEEDBACK,
    INTERVIEW,
    STUDENT_V2,
    UNIVERSITY,
    COMMUNICATION,
    UNIVERSITY_MAP,
    RECOMMENDATION,
    INTERNSHIP_OFFER,
    SPONTANEOUS_APPLICATION,
    INTERVIEW,
    INTERVIEW_TEMPLATE,
    INTERNSHIP_POS_OFFER,
    SPONTANEOUS_APPLICATION,
    RECOMMENDATION_UPDATED_STATUS,
}
