package click.studentandcompanies.dto;

public enum DTOTypes {
    CV,
    ERROR,
    EMPTY,
    STUDENT,
    FEEDBACK,
    STUDENT_V2,
    UNIVERSITY,
    COMMUNICATION,
    RECOMMENDATION,
    INTERNSHIP_OFFER,
    SPONTANEOUS_APPLICATION,
    RECOMMENDATION_UPDATED_STATUS,
    INTERVIEW
}
